modLoader="javafml"
loaderVersion="[28,)"
license="All rights reserved"
issueTrackerURL="https://github.com/vanlueckn/TCUtility/issues"

[[mods]]
modId="tcutility"
version="${version}"
displayName="TC Utility"
updateJSONURL=""
displayURL="https://discord.gg/Um97SHnrYp"
authors="Jeronimo"
description='''
TC Utility provides JSON-driven block, item, fluid and armor registration.
'''

[[dependencies.tcutility]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tcutility]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,1.15)"
    ordering="NONE"
    side="BOTH"
